[package]
name = "bevy_wgsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"

[dev-dependencies]
bevy = "0.12"
bevy_egui = "0.23.0"